### ISSUE TITLE
ExpandCssUrls does not escape/unescape URLs before writing/reading

### ISSUE THREAD

**Issue by ArturDorochowicz** [andrewdavey/cassette#342]
This was observed on Cassette 2.1.0 beta 3
### Problem on the reading side

Given a file structure like this:

```
/Content/my dir/image.png
/Content/site.css
```

where site.css is:

``` css
body {
    background-image: url('my%20dir/image.png')
}
```

The result of Cassette's processing is (debug=true):

``` css
body {
    background-image: url('/Content/my%20dir/image.png')
}
```

The problem here is that the image file does not have hash value added. This is because Cassette fails to find image.png, because it treats the URL literally as path and looks for directory named 'my%20dir'.

Of course, the space here is just an example, the whole URL could just as well be hex encoded.
### Problem on the writing side

Given a structure like this:

```
/Content/my dir/site.css
/Content/my dir/image.png
```

with site.css:

``` css
body {
    background-image: url(image.png);
}
```

(note lack of quotes, which is perfectly legal) and a bundle that includes site.css.

The result after processing (debug=true) is:

``` css
body {
    background-image: url(/cassette.axd/file/Content/my dir/image-da1c9bf45bd3644c2ddffcd4f631108d80e6a6f2.png);
}
```

Note that there is a space in 'my dir' that should be encoded. Apart from being incorrect, it actually causes a problem with AjaxMin which fails to process it correctly (OTOH if the input is wrong, it's free to do anything). (It works when the string is in quotes.)
The result with debug=false is the following:

``` css
body{background-image:dir/image-da1c9bf45bd3644c2ddffcd4f631108d80e6a6f2.png)}
```
### Fixing

As far as I know, for the writing side one can use Uri.EscapeUriString().
Not sure about the reading side, though. Uri.GetComponents() or Uri.LocalPath, may be helpful.
