### ISSUE TITLE
Referencing font from stylesheet throws FileNotFoundException when debug="false"

### ISSUE THREAD

**Issue by sfmskywalker** [andrewdavey/cassette#55]
I'm referencing a font from my stylesheet using: 

``` css
@font-face {
    font-family: 'PalindromeSSiRegular';
    src: url('../../fonts/pali1-webfont.eot');
    src: url('../../fonts/pali1-webfont.eot?#iefix') format('embedded-opentype'),
         url('../../fonts/pali1-webfont.woff') format('woff'),
         url('../../fonts/pali1-webfont.ttf') format('truetype'),
         url('../../fonts/pali1-webfont.svg#PalindromeSSiRegular') format('svg');
    font-weight: normal;
    font-style: normal;

}
```

When I request my page with debug="false", I receive the following exception:

_System.IO.FileNotFoundException:_

_Could not find file 'C:\Projects\The Dutch Pirates\PBCommunity\trunk\Applications\Web\PBCommunity\PBCommunity\Content\fonts\pali1-webfont.svg#PalindromeSSiRegular'._
